### ISSUE TITLE
Do we need UCLouvain-CBIO/rWSBIM1207?

### ISSUE THREAD

**Issue by csoneson** [carpentries-incubator/bioc-intro#116]
Is it necessary to install `UCLouvain-CBIO/rWSBIM1207` for this lesson (in https://github.com/carpentries-incubator/bioc-intro/blob/main/learners/setup.md)? I don't think it is loaded anywhere (accessing the messy data set is done via GitHub).

**Comment by lgatto** [comment]
Indeed, it's not anymore. We used it initially for the example data in the table joins, but now provide URLs to directly download them.

**Comment by lgatto** [comment]
I'll fix it right away.
