### ISSUE TITLE
An error in "Starting with data" lesson

### ISSUE THREAD

**Issue by denver3500** [carpentries-incubator/bioc-intro#130]
For the challenge - 
"Based on the output of str(rna), can you answer the following questions?
What is the class of the object rna?
How many rows and how many columns are in this object?"

The answer in the lesson is "how many rows: 66465, how many columns: 11"

But the output of str(rna) is `data.frame': 32428 obs. of  19 variables`, which is also indicated in the lesson itself 2 paragraphs above. Shound't the answer be - rows: 32428, columns: 19?

**Comment by lgatto** [comment]
Indeed, you are right. The 66465 and 11 are remnants of an old dataset.

I'll fix it right away.
