### ISSUE TITLE
Timings

### ISSUE THREAD

**Issue by lgatto** [carpentries-incubator/bioc-intro#19]
Add lesson timings - to discuss with Axelle

**Comment by tobyhodges** [comment]
@lgatto you mentioned in a Bioconductor Teaching Committee meeting today that the lesson is designed to be taught over two days. If you want to, you can specify the starting points of each day in the schedule by adding a `start: true` to the YAML header of the first episode on each day - this will result in a new column in the schedule table on the `index.html` page of the lesson, showing "Day 1", "Day 2", etc. (See [the Instructor Training curriculum](https://carpentries.github.io/instructor-training/) for example.)

**Comment by jdrnevich** [comment]
Leaving a comment here to bump this up - any way these can be in by the demo workshop on Thursday?
