### ISSUE TITLE
make headings more accessible

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/bioc-intro#20]
Many of the episodes include section headings at the `h1` level in the page source. [To make the lesson more accessible for visitors using a screen reader, pages should contain only one top-level heading.](https://www.a11yproject.com/posts/how-to-accessible-heading-structure/) This is provided by the lesson template, based on the `title` field in the Rmd metadata. All other sections should be `h2` or below (i.e. `## section title` in the Rmd source) - I started a branch, `accessible-headings`, which I will work on to adjust the headings in all the episodes so far.

**Comment by lgatto** [comment]
Thank you!
