### ISSUE TITLE
tidyverse on SEs

### ISSUE THREAD

**Issue by lgatto** [carpentries-incubator/bioc-intro#4]
A lesson to use tidyverse-style packages directly on SummarizedExperiment objects? 

Suggested by Hugo at Bioc 2021.

**Comment by lgatto** [comment]
There now is a short section at the end of the last chapter. I am wondering whether this is useful or confusing for the students. Should we mention it and point to the `tidySummarizedExperiment` vignette or other relevant material? Should we leave it and skip if we don't have time? 

@csoneson @jdrnevich @mblue9, what do you think?

**Comment by csoneson** [comment]
I would lean towards keeping it - maybe it makes the link to the rest of the course a bit clearer?
