### ISSUE TITLE
Error building website

### ISSUE THREAD

**Issue by mchiapello** [carpentries-incubator/bioc-intro#5]
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

I got the following error after build the page:

`chmod: cannot access '/opt/R/4.1.0/lib/R/library': No such file or directory`

Any idea how to get rid of it?
M

**Comment by mchiapello** [comment]
I enabled github actions. The website build was triggered by a push. 

The goal was to build my forked repository. I just did a minor change for the push. 

I saw you got the same error in the last github action run.

**Comment by lgatto** [comment]
Ah, ok, thanks. Will look into it.

**Comment by fmichonneau** [comment]
Hello all,

it looks like a bug in the GitHub actions. We have improved the scripts in the GitHub Actions compared to the version that is available in the Carpentries Incubator template, so I'm going to open a pull request to bring these changes to your lesson, which should make address this issue.
