### ISSUE TITLE
Update SE next steps

### ISSUE THREAD

**Issue by lgatto** [carpentries-incubator/bioc-intro#58]
SE was also very confusing, just very different from the rest of the material, and it was difficult for participants to conceptualise why/when this would be useful. Especially as the long format, as they were given, already contains all data. Maybe we could provide the 3 independent tables (matrix, col and row data) and they build the SE, which corresponds to reality. A summary exercise could then be to extract some counts for some features/sample from the SE and long table, and confirm they are identical.

**Comment by jdrnevich** [comment]
I would also say we need to add explicit checking that the samples are in the same order in matrix and col data, and the genes are in the same order in matrix and row data. Or does the SummarizeExperiment() constructor somehow check for this? I know from bitter experience that DGEList() does not!

**Comment by lgatto** [comment]
I think it complains of the assay's col names don't match the coldata's row names, but the latter could be missing (I believe). I suggest we make sure things *just works* to minimise the steps to get to that SE. Any intermediate step obfuscates the benefits of using an SE. We can mention these "details" in the text but should avoid complicating things.

**Comment by jdrnevich** [comment]
It's always a trade off of simplicity vs. reality. If their data set doesn't _just work_ then they won't be analyzing the data correctly. But I agree that a simple mention in the text of "(make sure your samples and genes are in the same order in all objects)" could be enough for this.

**Comment by lgatto** [comment]
This has been implemented now. There's a code chunk that checks row and col names (lines 173 and 174).
