### ISSUE TITLE
Highlighting keywords in plain text

### ISSUE THREAD

**Issue by ManonMartin** [carpentries-incubator/bioc-intro#63]
A minor comment but wouldn't it be a good idea to highlight important concepts/keywords in the plain text by putting words in bold rather than italics?

eg: 

The basis of programming is that we write down instructions for the computer to follow, and then we tell the computer to follow those instructions. We write, or **code**, instructions in R because it is a common language that both the computer and we can understand. We call the instructions **commands** and we tell the computer to follow the instructions by **executing** (also called **running**) those commands.

There are two main ways of interacting with R: by using the **console** or by using **scripts** (plain text files that contain your code). The console pane (in RStudio, the bottom left panel) is the place where commands written in the R language can be typed and executed immediately by the computer. It is also where the results will be shown for commands that have been executed. You can type commands directly into the console and press Enter to execute those commands, but they will be forgotten when you close the session.

Instead of:

The basis of programming is that we write down instructions for the computer to follow, and then we tell the computer to follow those instructions. We write, or _code_, instructions in R because it is a common language that both the computer and we can understand. We call the instructions _commands_ and we tell the computer to follow the instructions by _executing_ (also called _running_) those commands.

There are two main ways of interacting with R: by using the console or by using scripts (plain text files that contain your code). The console pane (in RStudio, the bottom left panel) is the place where commands written in the R language can be typed and executed immediately by the computer. It is also where the results will be shown for commands that have been executed. You can type commands directly into the console and press Enter to execute those commands, but they will be forgotten when you close the session.

**Comment by lgatto** [comment]
I like this. @csoneson, what do you think?
