### ISSUE TITLE
We need to include the references

### ISSUE THREAD

**Issue by ManonMartin** [carpentries-incubator/bioc-intro#65]
There is no reference file (.bib) present in the repo, the references are not pointing to an actual bibliography item. For instance `@Zeeberg:2004` in "Starting with data".

**Comment by lgatto** [comment]
Thanks, added now. But I am not sure that the current infrastructure support references. We will be moving to the new [workbench](https://carpentries.github.io/workbench/), so this isn't a priority at the moment.
