### ISSUE TITLE
annot1.csv and annot2.csv are missing

### ISSUE THREAD

**Issue by jdrnevich** [carpentries-incubator/bioc-intro#74]
Found another problem: At the end of the https://carpentries-incubator.github.io/bioc-intro/30-dplyr/index.html, the codes say to read in `data/annot1.csv` and `data/annot2.csv` but I can't find anywhere in the workshop where the attendees have been told where to get these files. Am I missing it?

**Comment by lgatto** [comment]
There are links in the text that the participants can use to download the files. See below for `annot1`

![image](https://user-images.githubusercontent.com/384198/195764166-fb4e8b5b-3591-47f6-af4d-539283ece92e.png)

**Comment by tobyhodges** [comment]
Making the text for these links more informative would make the lesson [more accessible to people using a screen reader](https://www.w3.org/WAI/tips/writing/#make-link-text-meaningful) and I guess would also help ensure that anyone reading the text doesn't miss the point that they should download the data from there.

**Comment by jdrnevich** [comment]
Thanks. I am not sure I completely understood how best to word the text for a screen reader, but I also included R codes to download the files like we did for rnaseq.csv

**Comment by lgatto** [comment]
The links need to be updated - they point to a fork of the repo. Will do that now.
