### ISSUE TITLE
Transition to workbench

### ISSUE THREAD

**Issue by lgatto** [carpentries-incubator/bioc-intro#76]
Dear [@zkamvar](https://github.com/zkamvar)

When you get a chance, could you please help me transition this repository to the workbench format? I had a first go at it [here](https://github.com/lgatto/workbench-bioc-intro). I didn't get very far due to limited time, without any plan for the legacy version to transition to workbench - your latest video indicates that there is a roadmap to help with this. 

Many thanks in advance and do let me know if I can help. 

Laurent

**Comment by zkamvar** [comment]
Hi @lgatto, 

I can certainly help. I'll add your repo to https://github.com/carpentries/lesson-tranisition

**Comment by lgatto** [comment]
Hi @zkamvar - let me know if there's anything I can do. 

FYI - We are preparing a list of authors/contributors/maintainers for a citations/zenodo DOI but plan to wait until the transition.

**Comment by zkamvar** [comment]
Thank you for reminding me! I apologise for not following through on this... this winter has not been kind to me. 

Would you be okay if we convert your lesson next week? I am playing a bit of catch up right now. 

One thing that I would appreciate is if you could try cloning https://github.com/fishtree-attempt/bioc-intro/ locally and see if you can build it. You can find [installation instructions](https://carpentries.github.io/workbench/#installation) and then use `sandpaper::serve()` to provision the packages and build the lesson locally.

## Background

When I set up your lesson, I found that there was a bootstrapping bug with BioConductor lessons (https://github.com/carpentries/sandpaper/issues/365) that traced back to a bug in {renv} (https://github.com/rstudio/renv/issues/1110).

The good news is that I was able to get around this bug by manually provisioning the Bioc repos (see https://github.com/fishtree-attempt/bioc-intro/commit/b5572fb4e1b798b73aee6e5906fcbb2fb9ec49c4) and this lesson appears to be working well: https://fishtree-attempt.github.io/bioc-intro/60-next-steps.html

You can even see the automated pull request showing how things change with updated packages: https://github.com/fishtree-attempt/bioc-intro/pull/2

**Comment by lgatto** [comment]
Hi @zkamvar - no need to apologise, thank you for your efforts. Next week would be great, but there's no hurry. 

I'll clone and test a local build. Will update you here.

**Comment by lgatto** [comment]
Just to let you know that it builds and displays successfully locally. Would like me (or the wider education team) to look into it more carefully and provide feedback?

**Comment by zkamvar** [comment]
> Just to let you know that it builds and displays successfully locally. Would like me (or the wider education team) to look into it more carefully and provide feedback?

That's wonderful! 

Here is some information about what you and the other maintainers who have write access can expect after the transition: https://carpentries.github.io/workbench/beta-phase.html#beta

**Comment by zkamvar** [comment]
I should be getting to the transition today. I was cleaning up a few things yesterday to make the transition a bit smoother (e.g. transforming raw github links to relative paths that will resolve correctly: https://github.com/carpentries/lesson-transition/blob/0478e2f8393bad6ceba70e0de6328d2c6d4f2ba2/carpentries-incubator/bioc-rnaseq.R#L21-L26).

I am going to send a message here notifying everyone on this repository about what to expect and then set all permissions to read except for @lgatto, so that they can give permissions. 


Here are some resources in the meantime:

1. What you can expect from the transition 📹: https://carpentries.github.io/workbench/beta-phase.html#beta
1. How to update your local clone 💻: https://carpentries.github.io/workbench/beta-phase.html#updating-clone
1. How to update (delete) your fork (if you have one) 📹: https://carpentries.github.io/workbench/faq.html#update-fork-from-styles

**Comment by zkamvar** [comment]
This lesson will be converted to use [The Carpentries Workbench][workbench]
To prevent accidental reversion of the changes, we are temporarily revoking
write access for all collaborators on this lesson:

 - [ ] @lgatto (admin)
 - [ ] @rcastelo (maintain)
 - [ ] @csoneson (maintain)
 - [ ] @jdrnevich (push)

If you no longer wish to have write access to this repository, you do not
need to do anything further.

1. What you can expect from the transition 📹: https://carpentries.github.io/workbench/beta-phase.html#beta
2. How to update your local clone 💻: https://carpentries.github.io/workbench/beta-phase.html#updating-clone
3. How to update (delete) your fork (if you have one) 📹: https://carpentries.github.io/workbench/faq.html#update-fork-from-styles

If you wish to regain write access, please re-clone the repository on your machine and
then comment here with `I am ready for write access :rocket:` and the
admin maintainer of this repository will restore your permissions.

If you have any questions, please reply here and tag @zkamvar

[workbench]: https://carpentries.github.io/workbench

**Comment by zkamvar** [comment]
The deed is done. @lgatto, the infrastructure takes [a few minutes to bootstrap and cache the packages for the lesson build](https://github.com/carpentries-incubator/bioc-intro/actions/runs/4208062991/jobs/7303642937)). Once the build is done, I will switch github pages to deploy from the `gh-pages` branch and you will have your workbench lesson. 

Thank you all for your enthusiasm and your patience!

**Comment by zkamvar** [comment]
Whoops. I didn't mean to close this, only reference 😳.

**Comment by zkamvar** [comment]
The Workbench version is now live: https://carpentries-incubator.github.io/bioc-intro/

In addition, here is [map of commits that were changed during the transition](https://github.com/carpentries/lesson-transition/blob/52c40f631e3dd3973b40e81bd7c9a03a88997aae/release/carpentries-incubator/bioc-intro-commit-map.hash)

**Comment by lgatto** [comment]
This is great, thank you very much @zkamvar !
