### ISSUE TITLE
Change in rnaseq.csv requiring addition of quote = "" to read in?

### ISSUE THREAD

**Issue by jdrnevich** [carpentries-incubator/bioc-intro#89]
UPDATE:  I figured out that I had just copied the link from my browser which had "blob" instead of "raw". You can decline the 2nd and 3rd pull requests I put in. The first one should be modified to change blob to raw in the url path. But still is better to read in the copy with this repo instead of our other bioconductor-teaching repo.

**Comment by lgatto** [comment]
Just seeing this after commenting on the PR. I can't reproduce this... are you sure your file isn't corrupted?
