### ISSUE TITLE
Blob instead of raw file being downloaded

### ISSUE THREAD

**Issue by csmagnano** [carpentries-incubator/bioc-intro#94]
In the Starting with Data lesson, [on line 74](https://github.com/carpentries-incubator/bioc-intro/blob/a9ec2f7c86d1998e2b905eaa36200c10f3638b73/episodes/25-starting-with-data.Rmd#L74), 'https://github.com/carpentries-incubator/bioc-intro/blob/main/episodes/data/rnaseq.csv' is currently downloaded, which downloads the webpage instead of the datafile. 

Instead, 'https://github.com/carpentries-incubator/bioc-intro/raw/main/episodes/data/rnaseq.csv' should be the download url to get the raw csv file.

**Comment by lgatto** [comment]
Indeed, very sorry about that. Your PR is being tested and I'll merge asap.

**Comment by jdrnevich** [comment]
That would be my fault! I used blob instead of raw in my original PR. I think I mentioned it but didn't change the PR once I realized it was wrong.

**Comment by lgatto** [comment]
No worries - the PR has been merged and the updated rendered version should be up in a few minutes. I should have caught it, but there were other issues with the building that distracted med.
